# Generated by Django 5.0.3 on 2024-03-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fac_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fac_dept', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=100)),
                ('std_dept', models.CharField(max_length=20)),
                ('std_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('fac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world_app.faculty')),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_dept_id', to='hello_world_app.department')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_dept_name', to='hello_world_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Proctor',
            fields=[
                ('pctr_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pctr_name', models.CharField(max_length=15)),
                ('pctr_phone', models.CharField(max_length=15)),
                ('pctr_dept', models.CharField(max_length=20)),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_name', models.CharField(max_length=100)),
                ('par_phone', models.CharField(max_length=15)),
                ('par_address', models.TextField()),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world_app.student')),
            ],
        ),
    ]
